name: DrSleep
version: ${project.version}
main: org.acornmc.drsleep.DrSleep
api-version: 1.17
authors: [DrBot]
description: A fair sleeping solution
commands:
  nosleep:
    description: adds you to the nosleep list
    usage: /<command>
    permission: drsleep.nosleep
  drsleep:
    description: DrSleep admin commands
    usage: /<command> <reload|clear|list>
    permission: drsleep.admin
  sleep:
    description: makes you sleep without a bed
    usage: /<command>
    permission: drsleep.sleep
  togglephantoms:
    description: togglephantoms
    usage: /<command>
    permission: drsleep.togglephantoms
permissions:
  drsleep.nosleep:
    description: use the nosleep command
    default: op
  drsleep.list:
    description: list the players on nosleep
    default: op
  drsleep.clear:
    description: clears the drsleep list
    default: op
  drsleep.reload:
    description: reloads DrSleep
    default: op
  drsleep.sleep:
    description: use the sleep command
    default: op
  drsleep.togglephantoms:
    description: use the togglephantoms  command
    default: op
  drsleep.admin:
    description: use admin commands
    default: op
