name: DrSleep
version: ${project.version}
main: org.acornmc.drsleep.DrSleep
api-version: 1.19
authors: [DrBot]
description: A fair sleeping solution
load: STARTUP
commands:
  allowsleep:
    description: adds you to the nosleep list
    usage: /<command>
    permission: drsleep.preventsleep
  preventsleep:
    description: adds you to the nosleep list
    usage: /<command>
    permission: drsleep.preventsleep
  togglesleep:
    description: toggles you on the nosleep list
    usage: /<command>
    permission: drsleep.preventsleep
  drsleep:
    description: DrSleep admin commands
    usage: /<command> <reload|clear|list>
    permission: drsleep.admin
permissions:
  drsleep.nosleep:
    description: use the preventsleep and allowsleep commands DEPRECATED
    default: false
    children:
      - drsleep.preventsleep
  drsleep.list:
    description: list the players preventing sleep
    default: op
    children:
      - drsleep.admin
  drsleep.clear:
    description: clears the drsleep list
    default: op
    children:
      - drsleep.admin
  drsleep.reload:
    description: reloads DrSleep
    default: op
    children:
      - drsleep.admin
